#!/usr/bin/env bash
# WALLPAPER_DIR="$HOME/Imagens/wallpapers/"
# CURRENT_WALL=$(hyprctl hyprpaper listloaded)

# Get a random wallpaper that is not the current one
# WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

# Apply the selected wallpaper
# hyprctl hyprpaper reload ,"$WALLPAPER"
preload = /home/haruo/Imagens/wallpapers/astronaut_w_balloons_1280x720.png
wallpaper = eDP-1,/home/haruo/Imagens/wallpapers/astronaut_w_balloons_1280x720.png 

hyprctl hyprpaper wallpaper
